version: '3'

services:
  backend:
    container_name: multimedia_backend
    restart: always
    build: ./
    ports:
      - 3300:3300
    networks:
      - network-multimedia
    env_file: ./.env

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      MYSQL_DATABASE: example_db
    ports:
      - "3306:3306"

networks:
  network-multimedia:
    driver: bridge